# This is a basic workflow to help you get started with Actions

name: sync-gh-pages

# Controls when the workflow will run
on:
  push:
    branches: [main]
  schedule:
    - cron: '0 3 * * *' # At 02:00 AM

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: repo-sync
      uses: repo-sync/github-sync@v2
      with:
        source_repo: "https://${env.access_token}@github.com/usatko/al-folio/tree/gh-pages"
        source_branch: "gh-pages"
        destination_branch: "gh-pages"
        github_token: ${{ secrets.PAT }}
